export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const SET_FILTER_PRODUCTS = 'SET_FILTER_PRODUCTS'


export const SET_HOMBRE_PRODUCTS = 'SET_HOMBRE_PRODUCTS'
export const SET_MUJER_PRODUCTS = 'SET_MUJER_PRODUCTS'
export const SET_NINO_PRODUCTS = 'SET_NINO_PRODUCTS'

export const ADD_ARTICLES = 'ADD_ARTICLES'