export const MAN = 'Hombre'
export const WOMAN = 'Mujer'
export const BOY = 'NIÑO'
export const COLLECTIONS = 'Colecciones'
export const US = 'Nosotros'
export const NEWS = 'Noticias'
export const NEW = 'Noticia'
export const CONTACT = 'Contacto'